[install]
registry = { url = "https://registry.npmjs.org/", token = "$BUN_AUTH_TOKEN" }
linker = "hoisted"

[test]
# Specify root directory for test discovery
# When running `bun test` from root, only look in pickier package
root = "./packages/pickier"
